### ISSUE TITLE
Can't get importing to work

### ISSUE THREAD

**Issue by eltiare** [benbowes/react-responsive-select#1]
When I try to use `import ReactResponsiveSelect from 'ReactResponsiveSelect';` after installing `react-responsive-select` I get a message that the module cannot be found. If I change `'ReactResponsiveSelect'` to `'react-responsive-select'` all it imports is an empty object and throws other errors when I attempt to use it.

**Comment by benbowes** [comment]
Thanks @eltiare I'm checking this out now.

**Comment by benbowes** [comment]
@eltiare I can see the problem, and you are right about the import.

I will have to update the package. And remove the inbuilt demo (that I think, is what has caused the problem). 

I have resolved it locally by calling the `src` directly. Which means I have to babel transpile all the things in my node_modules folder. Not ideal.

Thanks for highlighting this.

```
import React, { Component } from 'react';
import ReactDOM from 'react-dom';
import ReactResponsiveSelect from 'react-responsive-select/src/ReactResponsiveSelect';

class Form extends Component {

  reportChange(newValue) {
    console.log(newValue);
  }

  render() {
    return (
      <form ref={r => this.form = r}>

        <ReactResponsiveSelect
          caretIcon={<span style={{float:'right'}}>+</span>}
          name="make"
          options={[
            { text: 'Any', value: 'null' },
            { text: 'Oldsmobile', value: 'oldsmobile', markup: <span>Oldsmobile</span> },
            { text: 'Ford', value: 'ford', markup: <span>Ford</span> }
          ]}
          onChange={this.reportChange}
          onSubmit={() => { this.form.submit(); }}
          prefix="Make:"
          selectedValue="mazda"
        />

      </form>
    );
  }
}

ReactDOM.render(
  <Form />,
  document.getElementById('root')
);
```
