### ISSUE TITLE
noSelectionLabel

### ISSUE THREAD

**Issue by Konstantin6487** [benbowes/react-responsive-select#104]
Hi! 
I use react-typescript. It's all ok, but i recieved an error on *noSelectionLabel* attr: 
```
 Property 'noSelectionLabel' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<ReactResponsiveSelect> & Readonly<{ children?: ReactNode; }> & Readonly<IProps>'.
```
I can use `// @ts-ignore`, but it's not a good practise. What can i do?
Sorry for my english :)

**Comment by benbowes** [comment]
Thanks @Konstantin6487 totally true.

I plan to rewrite the this repo to typescript.

In the meantime I shall add this to the index.d.ts

**Comment by benbowes** [comment]
Hi @Konstantin6487,

I have added `noSelectionLabel?: string;` to `react-responsive-select@4.5.7` via https://github.com/benbowes/react-responsive-select/pull/105
