### ISSUE TITLE
Keyboard input doesn't trigger change

### ISSUE THREAD

**Issue by jdwillemse** [benbowes/react-responsive-select#107]
When using a keyboard to change input the onChange event is fired every time a user presses up or down key. This is does not correlate with native behaviour when change is only triggered when spacebar or enter is hit. 

Why does this lib follow a different pattern? 

How can I get the onChange event to fire when a user confirms their selection by hitting space/enter?

**Comment by smcfarland-cs** [comment]
I've been looking into this as well and have found that this behavior changed with the 4.5.2 release. In 4.5.0 and earlier the onChange event is only fired when the option is actually selected with space or enter, not when it is highlighted with the keyboard.

**Comment by benbowes** [comment]
Thanks for looking into where the onChange functionality changes.

I agree, the functionality in 4.5.0 is best.

It'll be a month before I can tackle this. But I do want to do it.

**Comment by benbowes** [comment]
Hi @jdwillemse and @smcfarland-cs 

On initial investigation it looks like all I need to do is delete these lines in the reducer
https://github.com/benbowes/react-responsive-select/blob/master/src/reducers/reducer.js#L128-L131

I'll need to test this out a bit more, but if this is the fix, ETA is next few days.

**Comment by benbowes** [comment]
I have released a bugfix for this via a patch version 4.5.9 on npm.

Feel free to reopen if the fix does not meet requirements.

Thanks for your help @jdwillemse and @smcfarland-cs.
