### ISSUE TITLE
Markup Input Focus

### ISSUE THREAD

**Issue by claude39** [benbowes/react-responsive-select#112]
I can't access the input element inside the rowData. Does anybody know how to do it?

This is the content of rowData:

`{ text: 'Search', value: 'foo', markup: <input type="text" id="merchantSearch" placeholder="Search Merchant" value={keyword} onChange={handleInputChange} /> }`

**Comment by benbowes** [comment]
Hi @claude39 a couple of things... 

I have set pointer-events to none here https://github.com/benbowes/react-responsive-select/blob/master/dist/ReactResponsiveSelect.css#L112-L114 so using any interactive markup is going to be hard. This is a design choice. There are a few React Select components out there, I want this one to be as accessible as possible. So some limitations exist to help ensure that I can make this thing as close as possible to the native select, and also to limit the set of criteria to maintain.

The other thing. This issue has highlighted that the README is incorrect with what it says the `customLabelRenderer` prop returns. The README says that you should get the markup back (if you have used `markup` in an option). when you call, customLabelRenderer - customLabelRenderer no longer sends back the markup.

**Comment by benbowes** [comment]
I removed `markup` from the `customLabelRenderer`. I intend to remove from the README the part in the API that says customLabelRenderer returns `markup: JSX Object`

I never saw how this could be useful/reasonable. Sadly didn't cross reference with the README

**Comment by claude39** [comment]
Thanks @benbowes you can close this now.
