### ISSUE TITLE
nextPotentialSelectionIndex not updating to same value as singleSelectSelectedIndex and singleSelectInitialIndex 

### ISSUE THREAD

**Issue by BallardB** [benbowes/react-responsive-select#117]
Hello! 

I am experiencing an issue where nextPotentialSelectionIndex is not updating to the same value as singleSelectSelectedIndex and singleSelectInitialIndex.  

**Context:** 
I am using 2 React-responsive single selects to select the date range on a data visualization I am building. The data is in the form of years and quarters. Each year has anywhere from 1-4 quarters associated with that specific year. 

The first select allows the user to choose a year.  
The second select allows the user to choose a quarter from a list of available quarters for that specific year. 

For examples' sake here is the overall data:
`data: [
            {
                year: 2000,
                quarters: [1, 2, 3, 4]
            },
            {
                year: 2001,
                quarters: [1, 2, 3]
            },
        ]
`

The Data that is used for the year options: 
`
years: [
            {text: 2000, value: 2000},
            {text: 2001, value: 2001}
        ]
`

The data that is used for the quarter options when the year 2000 is selected from the 1st dropdown: 
`
quarters: [
            {text: 1, value: 1},
            {text: 2, value: 2},
            {text: 3, value: 3},
            {text: 4, value: 4}
        ]
`

The data that is used for the quarter options when the year 2001 is selected from the 1st dropdown: 
`
quarters: [
            {text: 1, value: 1},
            {text: 2, value: 2},
            {text: 3, value: 3}
        ]
`

- If the user selected the year `2000`, then the user could select from the 2nd dropdown quarters `1, 2, 3 or 4` 

- If the user selected the year `2001`, then the user could select from the 2nd dropdown quarters `1, 2, 3` 

- Upon first render of the application, the 1st dropdown will have the preselected value of `2000` and the 2nd dropdown will have the preselected value of `1`, indicating that the year 2000, Q1 is the initial state.

**Issue**

- After the initial render (selected year is 2000, selected quarter is 1), the user selects quarter 4 from the second dropdown. 

- If the user then selects year 2001 from the first dropdown, the quarter dropdown will re-render to only have the options of choosing quarters 1-3. **Initially** quarter 1 is displayed, which is the expected behavior.  

- Using react-chrome-devtools, I can see that the nextPotentialSelectionIndex displays value 4 whereas singleSelectSelectedIndex and singleSelectInitialIndex display value 1. The **nextPotentialSelectionIndex** is **out of sync** with the singleSelectSelectedIndex and singleSelectInitialIndex. 

- Upon clicking the 2nd dropdown, it tries to render value 4, but value 4 does not exist as an option, because the user selected 2001 from the 1st dropdown and 2001 only has the options 1 - 3. 

- Upon clicking the 2nd dropdown again the **nextPotentialSelectionIndex** then gets in sync with singleSelectSelectedIndex and singleSelectInitialIndex. Value 1 is displayed as the selected option again. nextPotentialSelectionIndex, singleSelectSelectedIndex and singleSelectInitialIndex all reference value 1. 

I don't know if I am missing something in the onChange() function to update this piece of data, but I can't seem to figure out how to solve this issue.

Please let me know if you need further information. Thank you for your help!

**Comment by benbowes** [comment]
Hi @BallardB, I am having a look at this now. Thanks for all of the detail 👍

**Comment by benbowes** [comment]
Hello again @BallardB, I made an example https://codesandbox.io/s/l4l37j2xv9

I believe that I could see the issue you mentioned. The next nextPotentialSelectionIndex was not updating. I added a `key` attribute in the above example to `react-responsive-select` that would change based on the year selected. Changing the key forces a reset within the quarters dropdown. Removing this key should show the issue you state above - if I understand the issue correctly.

e.g. 

```
<div className="App">
      <RRS
          selectedValue={selectedYear}
          name="year"
          options={years}
          onChange={this.onChangeYear}
      />
      <RRS
          key={selectedYear} // Added key
          selectedValue={selectedQuarter}
          name="quarters"
          options={quarters}
          onChange={this.onChangeQuarter}
      />
</div>
```

Please let me know how it goes, Ben

**Comment by BallardB** [comment]
Hi @benbowes, 

Thanks for the quick response. Adding the key attribute definitely solves the issue I was seeing and makes both dropdowns work seamlessly together.  Thanks again for your help!

**Comment by benbowes** [comment]
Thanks @BallardB,

I realise now that I need a better example of using rrs as a controlled component.

Your example is a good example, so will use this going forward. I have implemented it here (next version): https://benbowes.github.io/react-responsive-select-next/?path=/story/controlled--using-rrs-as-a-controlled-component
