### ISSUE TITLE
onChange() Event Handler Firing Twice 

### ISSUE THREAD

**Issue by BallardB** [benbowes/react-responsive-select#118]
Hello again! 

I'm running into an issue where the onChange() event handler is firing twice upon making a selection. Building upon the scenario given in https://github.com/benbowes/react-responsive-select/issues/117, here is the updated context: 

I am using 3 react-responsive single selects to select a start and end date range for a data visualization. Data is in form of years and quarters, where each year has anywhere from 1-4 quarters associated with that specific year. 

The first two dropdowns, `start year` and `start quarter` control the start range. 

The third dropdown, `end year`, controls the end range. 

Every time a user makes a new selection from one of these dropdowns, a chart is updated to display the newly selected date range and its associated data.

**Updated Data Structures:** 

The quarterData shows that for each year/quarter pair any amount of data could be associated with it, ie. GDPGrowth, GDPPlus, attrition, ect.
const quarterData = [
     { year: 2000, quarter: 1, GDPGrowth: 1.3 },
     { year: 2000, quarter: 2, GDPGrowth: -2 },
     { year: 2001, quarter: 1, GDPGrowth: 2.5 },
     { year: 2002, quarter: 1, GDPGrowth: 4.5 },
     { year: 2002, quarter: 2, GDPGrowth: 2.8 },
     { year: 2002, quarter: 3, GDPGrowth: -3.2 },
     { year: 2002, quarter: 4, GDPGrowth: -0.1 },
     { year: 2003, quarter: 1, GDPGrowth: 4.5 },
     { year: 2003, quarter: 2, GDPGrowth: 2.8 },
     { year: 2003, quarter: 3, GDPGrowth: -3.2 },
     { year: 2003, quarter: 4, GDPGrowth: -0.1 },
     { year: 2004, quarter: 1, GDPGrowth: 4.5 },
     { year: 2004, quarter: 2, GDPGrowth: 2.8 },
     { year: 2004, quarter: 3, GDPGrowth: -3.2 },
     { year: 2004, quarter: 4, GDPGrowth: -0.1 },
     { year: 2005, quarter: 1, GDPGrowth: -0.9 }
];

In this data set, we have the associated quarters for each year options. Each quarter has its index in the `quarterData` dataset. 
const yearData = [
  {
    year: 2000,
    quarters: [{ quarter: 1, index: 0 }, { quarter: 2, index: 1 }],
    yearIndex: 0
  },
  {
    year: 2001,
    quarters: [{ quarter: 1, index: 2 }],
    yearIndex: 1
  },
  {
    year: 2002,
    quarters: [
      { quarter: 1, index: 3 },
      { quarter: 2, index: 4 },
      { quarter: 3, index: 5 },
      { quarter: 4, index: 6 }
    ],
    yearIndex: 2
  },
  {
    year: 2003,
    quarters: [
      { quarter: 1, index: 7 },
      { quarter: 2, index: 8 },
      { quarter: 3, index: 9 },
      { quarter: 4, index: 10 }
    ],
    yearIndex: 3
  },
  {
    year: 2004,
    quarters: [
      { quarter: 1, index: 11 },
      { quarter: 2, index: 12 },
      { quarter: 3, index: 13 },
      { quarter: 4, index: 14 }
    ],
    yearIndex: 4
  },
  { year: 2005, quarters: [{ quarter: 1, index: 15 }], yearIndex: 5 }
];

The Data that would used for the start year options:
The value corresponds to the years' index in the `yearData` array.
**years:** [ {text: 2000, value: 0}, {text: 2001, value: 1}, {text: 2002, value: 2}, {text: 2003, value: 3}, 
{text: 2004, value: 4}, {text: 2005, value: 5} ]

The data that is used for the quarter options when the year 2000 is selected from the start year dropdown:
The value corresponds to the quarter's index in the `quarterData` array
**quarters:** [ {text: 1, value: 0}, {text: 2, value: 1} ]

It is also helpful to know the rules for displaying data that influence how the dropdowns function. 

1. The user cannot select a year in the past from the end year dropdowm
        a. We limit the end year options to ensure the user never selects a year from the end year dropdown that is earlier than the start year dropdown. 
        b. Every time the user selects a new start year, the end year options will update accordingly 

2. At least 1 quarter of data must be used to power the data visualization
        a. For example, if a start year only has one quarter available, we do not allow the user to select that same year as an end year because that would mean that the range from the start year/quarter to the end year could not display more than one quarter 
        b. I.e. Using the data above, if the user selected the start year as 2001, we would not allow the user to select 2001 from the end year dropdown because 2001 only has one available quarter of data 

3. If the user selects a year/quarter in the future (ie. the start year is greater than the end year), then we either: 
        a. If the last quarter in the start is selected, then we push the selected year by one more than newly selected start year.
        b. Set the end year to be the newly selected start year 
        c. For example: 
               i. 2001 Q1 is the Start and 2002 is the End 
               ii. The user selects a start year of 2003 
               iii. This date is in the future, the new start year will be 2003 and the new start quarter will be the first available quarter, Q1. The last quarter is not selected, so the new end year will be 2003 
               iv. If the user then selects Q4, without changing the start year, the new start will be 2003 Q4, to satisfy the rule of displaying at least 1 quarter of data, the end year must be pushed to 2004.

**With this context in mind, here is the issue at hand:** 
The event handler for `this.onChangeEndYear` is firing twice every selection. I think the issue stems from the `key` attribute set to the end-year react-responsive single select.

- if the key is set to a static variable, ie. `key={2}`
    - event handler only fires twice when selecting the first year in the dataset, 2000
    - it fires to update the end-year to the year 2000, it then fires again to update the end-year as 2005. Upon clicking the end-year dropdown, it displays the year 2000. Then clicking the end-year dropdown, it displays the year 2005. 
- if the key is set to a dynamic variable, it must be set to a key that will not clash with the `start-quarter` key, i.e. `key = {endSelectedYear.yearIndex}
    - the onChange() event handler fires twice when selecting any year from the end-year dropdown 
    - it only causes UI issues when selecting the first year in the dataset, the year 2000
        - it fires to update the end-year to the year 2000, it then fires again to update the end-year as 2005. Upon clicking the end-year dropdown, it displays the year 2005 as the selected year and the UI will not update to display the correctly selected year, 2000. 

Here is a **codepen link** to the above issue I am describing: https://codesandbox.io/s/7jxjlly7jj

Please let me know if you need more context. Im happy to provide further information that will help get to the bottom of this issue. Thanks!!

**Comment by benbowes** [comment]
@BallardB checking this out with a sense of urgency. It does appear as something is not right with the onChange functionality when using in a controlled setting.

**Comment by BallardB** [comment]
@benbowes Thank you for taking a look at it. Let me know if you need any other information. I appreciate the quick response time.

**Comment by benbowes** [comment]
Hi @BallardB I was unable to fully understand your requirements, so decided to create an example which I thought was close but a bit simpler.

https://codesandbox.io/s/y28mw1kzov

There is a sequence to the above example:
1. Select a Brand
2. then Select a Model
3. then Select a Colour

I am wary of the onChange firing on first render, and will sort that out in version 5. I will put that into version 4 as it is a breaking change.

I don't think that the onChange firing on first render should stop any functionality from occurring though.

**Comment by BallardB** [comment]
Hi @benbowes, 

I see in your example, the onChange() handler is not firing twice. 

**Could you clarify how you set and use `key` attribute to help manage the state of the component?** 
I see in your example:  

- the `key` for the model is based on the selected brand.

- the `key` for the colour is based on the selected brand and the selected model. 
 
I have updated my codepen to more closely align to how you are using the `key` attribute: https://codesandbox.io/s/7jxjlly7jj
In my example: 

- the `key` for the start-quarter is now based on the start-year 

- the `key` for the end-year is now based on the start-year and the start-quarter

I am still seeing the onChange() event handler firing twice for the end-year dropdown when selecting the first year in the data set, the year `2000`. 

**Any ideas on why this would be happening?** 

Thanks again for your help!

**Comment by benbowes** [comment]
I am not sure why that is happening. It is possible for you to try more shallow state?

**Comment by benbowes** [comment]
Hi @BallardB,

I have being doing some work to remove the first fire of onChange in the next version (5.0.0).

PR here:
https://github.com/benbowes/react-responsive-select-next/pull/13

Storybook here:
https://benbowes.github.io/react-responsive-select-next/?path=/story/recipes--controlled-example-2 

NPM module here (version 5.0.0-alpha-18):
https://www.npmjs.com/package/react-responsive-select-next

A codesandbox here:
https://codesandbox.io/s/rrs-issue-118-6ygdu

**Comment by benbowes** [comment]
The codesandbox is no longer a WIP. I removed React.Context from the example as it was more complex than it needed to be.

**Comment by BallardB** [comment]
Thanks @benbowes for all the info and your help with this! I bet someone using this package will also find this useful in the future.

**Comment by benbowes** [comment]
@BallardB I agree, the more info the better.

The controlled example I provided was not very good. Because of your input, I now have something more useful. Thanks heaps!
