### ISSUE TITLE
Adding keys to ReactResponsiveSelect's menu items

### ISSUE THREAD

**Issue by Snorlite** [benbowes/react-responsive-select#138]
If I assign the prop `caretIcon` to a ReactResponsiveSelect component, the application freezes for a few seconds after each value change, and at the launch of the app the console returns this message:
```
index.js:1375 Warning: Each child in a list should have a unique "key" prop. See https://fb.me/react-warning-keys for more information.
```

If I don't assign the `caretIcon` prop, the application works fluently and it returns no warnings.
My CaretIcon component is identical to the one used in this repository:

```
const CaretIcon = () => (
    <svg
        className="caret-icon"
        x="0px"
        y="0px"
        width="11.848px"
        height="6.338px"
        viewBox="351.584 2118.292 11.848 6.338"
    >
        <g>
            <path d="M363.311,2118.414c-0.164-0.163-0.429-0.163-0.592,0l-5.205,5.216l-5.215-5.216c-0.163-0.163-0.429-0.163-0.592,0s-0.163,0.429,0,0.592l5.501,5.501c0.082,0.082,0.184,0.123,0.296,0.123c0.103,0,0.215-0.041,0.296-0.123l5.501-5.501C363.474,2118.843,363.474,2118.577,363.311,2118.414L363.311,2118.414z" />
        </g>
    </svg>
);
```

Since I think the warning is referring to the `li` elements with `role="menuitem"`, how do I add a key to them? Or is there another solution?

**Comment by benbowes** [comment]
I will look into this, but in the meantime this might help:
https://codesandbox.io/s/rrs-issue-118-6ygdu

**Comment by Snorlite** [comment]
> Hi @Snorlite
> 
> I will look into this, but in the meantime this might help:
> https://codesandbox.io/s/rrs-issue-118-6ygdu
> 
> Look at the Form.js file

Thank you.

I still don't find what I'm doing wrong, I'll copy the relevant part of my code:

```
import React, {Component} from 'react'
import ReactResponsiveSelect from 'react-responsive-select'
import '../styles/ReactResponsiveSelect.css'
import CaretIcon from './CaretIcon'

const parameterOptions = [
    { value: 'cycle', text: 'Cycle' },
    { value: 'degree', text: 'Degree' }
  ];

class Test extends Component {
    constructor(props) {
        super(props)
        this.state = {
            parameter: this.props.startChartParameter,
        }
        this.handleChartChange = this.handleChartChange.bind(this)
    }

    handleChartChange = selectedParameter => {
        this.setState({ parameter: selectedParameter.value });
    };

    render() {
        return
                                <ReactResponsiveSelect
                                    name="test"
                                    caretIcon={<CaretIcon/>}
                                    selectedValue={this.state.parameter}
                                    onChange={this.handleChartChange}
                                    options={parameterOptions}
                                />
    }

}

export default Test;
```
I'm not using the `form` tag since I don't actually want to submit anything, but if I add it the problem persists.

**Comment by benbowes** [comment]
Hi @Snorlite I have added a new example based on what you shared above with some comments https://codesandbox.io/s/rrs-issue-138-1tm7u

The problem is that RRS is expecting you have a unique key on the CaretIcon that is supplied i.e. instead of `caretIcon={<CaretIcon/>}`, it is expecting `caretIcon={<CaretIcon key="someUniqueKey" />}`

In the `CaretIcon.js` file I have added a function that automatically adds a unique key so that you don't have to, but this is only a temporary fix.

There are 2 options available to you:

1. Update your CaretIcon component to have the getUniqueKey function.
2. Or add a unique key to the CaretIcon you supply to the caretIcon prop (as shown above).

Both of these options are a bit annoying IMO, I will do something about this soon.

**Comment by Snorlite** [comment]
> Hi @Snorlite I have added a new example based on what you shared above with some comments https://codesandbox.io/s/rrs-issue-138-1tm7u
> 
> The problem is that RRS is expecting you have a unique key on the CaretIcon that is supplied i.e. instead of `caretIcon={<CaretIcon/>}`, it is expecting `caretIcon={<CaretIcon key="someUniqueKey" />}`
> 
> This is a bit annoying though in my opinion, I will do something about this soon.

I'm sorry, I edited the CaretIcon component based on yours but the problem is still present.

**Comment by benbowes** [comment]
Hi @Snorlite I did not realise you were actively looking at it. I edited CaretIcon shortly after making that comment - removing the changes in the CaretIcon component. Could you please check again?

**Comment by Snorlite** [comment]
> Hi @Snorlite I did not realise you were actively looking at it. I edited CaretIcon shortly after making that comment - removing the changes in the CaretIcon component. Could you please check again?

Yeah, sorry. The warning disappeared, but the application freeze not.
I actually found that deleting another component I used in my app that has nothing to do with RRS (ReactMapGL) solves it.
I have no idea why it happens.

**Comment by benbowes** [comment]
Well I am glad that part of it is sorted. Good luck with your project

**Comment by benbowes** [comment]
see https://github.com/benbowes/react-responsive-select/pull/150

**Comment by benbowes** [comment]
Done as part of 6.0.0
