### ISSUE TITLE
Deprecation warning due using componentWillReceiveProps

### ISSUE THREAD

**Issue by meliborn** [benbowes/react-responsive-select#139]
After upgrading to the new version of React I see this deprecation warning:
![image](https://user-images.githubusercontent.com/735194/73529751-4843b980-4428-11ea-9d26-73be1b980c04.png)
Is it possible to follow new changes and drop componentWillReceiveProps using?

**Comment by benbowes** [comment]
Good plan. Shall do

**Comment by benbowes** [comment]
Updated as part of https://github.com/benbowes/react-responsive-select/pull/140

Re-open if any problems
