### ISSUE TITLE
Replace Storybook with Styleguidist 

### ISSUE THREAD

**Issue by bbowes-ae** [benbowes/react-responsive-select#145]
I prefer Styleguidist these days over StoryBook as I find it better from a developer perspective.

- gives a great code editor inline; allowing developers the ability to experiment with various settings
- storybook is great for the "everybody", I want to skew my focus towards developers
- after considerable time with both platforms, I consider "styleguidist" to be the better of the two in terms of documenting components

**Comment by benbowes** [comment]
see https://github.com/benbowes/react-responsive-select/pull/150

**Comment by benbowes** [comment]
released in 6.0.0
