### ISSUE TITLE
Close button for Mobile view 

### ISSUE THREAD

**Issue by carlospence** [benbowes/react-responsive-select#149]
Can the mobile pop view have a close button ?

**Comment by benbowes** [comment]
Possibly. Certainly not currently possible. 

It currently requires a tap on the background in multi select mode. And either a selection or a tap on the background in single select mode.

Currently the modal view is all css driven - essentially the css resizes the dropdown panel.

**Comment by benbowes** [comment]
Hi @carlospence I have published a new version of https://www.npmjs.com/package/react-responsive-select-next

react-responsive-select-next@6.0.0-aplha.7

I have added a close button, and made the spread props changes to the svg's and added a formik multiselect example

**Comment by carlospence** [comment]
Ok will check it out and will get back to you

**Comment by benbowes** [comment]
A heads up. The close button I have implemented in react-responsive-select-next does not work in Safari yet because of the position fixed property

**Comment by benbowes** [comment]
@carlospence I have fixed the Safari CSS

**Comment by benbowes** [comment]
see https://github.com/benbowes/react-responsive-select/pull/150

**Comment by benbowes** [comment]
released in 6.0.0

**Comment by carlospence** [comment]
@benbowes Is it release in react-responsive-select or in -next

**Comment by carlospence** [comment]
@benbowes , thanks for all your efforts so far. I have checked it out and it is much more better now. Though I forked another multiselect library and added mobile close button and used in my previous situation. I just implemented yours now and it is quite good.

One quick question. What if you don't want a default "Any" or "None" as first item in your multiselect box. You just want to List just your items only, thus the first item must be selectable with other items. In your current model, you can't select the first Item with any other Item.

**Comment by benbowes** [comment]
@carlospence check the noSelectionLabel example
