### ISSUE TITLE
Error when reseting values with singleselect

### ISSUE THREAD

**Issue by Buba21** [benbowes/react-responsive-select#154]
I've using this component in a project for a client it has been working just fine, but i think i've stumbled in to a bug with the single select option. 
I have a couple of side filters that are being showed as singleselect or multiselect dropdowns, i also have a method that calls a function that reset the values in the redux store and returns them to their original values. All the multiselects work just fine but the single select although it updates its value to the original, visually it remains as the last picked option.
Filters with default values:
![1](https://user-images.githubusercontent.com/47480201/94928858-31c09700-04bc-11eb-999c-f825b27f099f.PNG)
![image](https://user-images.githubusercontent.com/47480201/94930050-c4ae0100-04bd-11eb-81a9-a2a3f1b5ca3b.png)
Filters with changed values in this case the singleselect one:
![2](https://user-images.githubusercontent.com/47480201/94928860-32592d80-04bc-11eb-827e-4992232fa8c8.PNG)
![image](https://user-images.githubusercontent.com/47480201/94930134-e5765680-04bd-11eb-8c1d-f6f2d64ad393.png)
After pushing the reset button singleselect doesnt update:
![3](https://user-images.githubusercontent.com/47480201/94928864-32592d80-04bc-11eb-8f96-3916a6e02746.PNG)
![image](https://user-images.githubusercontent.com/47480201/94930192-fa52ea00-04bd-11eb-8d4d-8ef4220f68f2.png)

And the relevant code
Html code:
 ` <div>
        <form>
          <Select
            name="Criticality"
            options={selectCriticality}
            caretIcon={<CaretIcon key="l5" />}
            prefix="Criticality: "
            onSelect={criticalitySelectSelection}
          />
        </form>
      </div>`

Function that calls the action from the reducer that resets the values:
`resetSideDependenciesFilters = () => {
	  const { sideFiltersFields, resetSideFilters } = this.props;
	  resetSideFilters().then(() => {
	    this.createSideFiltersDropdownFields(sideFiltersFields);
	  });
	};`
It although the component value is updated and has the correct value stored, its visual representation doesnt follow along, and this only happens with single select, since with multi select everything updates just fine, maybe because the multiselect dropdown uses the selectedValues props. But i have tried with the singleselect option and it also doesnt work so im at a loss here, hope i can get some help in debugging this rather annyoing case.

**Comment by benbowes** [comment]
Hi @Buba21 ,

Interesting. Let me have a look.

**Comment by benbowes** [comment]
Whilst I am looking I should mention that I'd typically change the `key` prop on the select I wanted to reset, so as to force a re-render of the component.

See http://localhost:6060/#/Recipes/Controlled%20example%201

I am looking to see if I can replicate the issue, but in the meantime the above may help you

**Comment by benbowes** [comment]
Could you try altering the Controlled Example 1 above with this code?

The difference is that the whole form is now wrapped with a component that has a `key`. When the `key` changes. It forces a re-render and thus resets the form back to it's initial value.

```
import { Select, CaretIcon } from '../../react-responsive-select'; // 'react-responsive-select'

const DATA = [
  { year: 2000, quarters: [1, 2, 3, 4] },
  { year: 2001, quarters: [1, 2, 3] },
  { year: 2002, quarters: [2, 3] },
  { year: 2004, quarters: [1, 4] },
  { year: 2005, quarters: [1, 2, 3, 4] },
];

const ControlledExample = ({ count, onReset }) => {
  const filteredYears = DATA.map(item => ({
    text: `${item.year}`,
    value: `${item.year}`,
  }));

  const extractQuarters = quarters =>
    quarters.map(quarter => ({
      text: `${quarter}`,
      value: `${quarter}`,
    }));

  const [years, setYears] = React.useState(filteredYears);

  const [quarters, setQuarters] = React.useState(extractQuarters(DATA[0].quarters));

  const [selectedYear, setSelectedYear] = React.useState(DATA[0].year.toString());

  const [selectedQuarter, setSelectedQuarter] = React.useState(DATA[0].quarters[0].toString());

  const onChangeYear = newValue => {
    const selectedYearDataFragment = DATA.find(item => item.year.toString() === newValue.value);

    setSelectedYear(newValue.value);
    setSelectedQuarter(selectedYearDataFragment.quarters[0].toString());
    setQuarters(extractQuarters(selectedYearDataFragment.quarters));
  };

  const onChangeQuarter = newValue => {
    setSelectedQuarter(newValue.value);
  };

  return (
    <form className="form">
      <div className="form__item">
        <label htmlFor="rrs-year-menu">Year</label>
        <Select
          selectedValue={selectedYear}
          name="year"
          options={years}
          onChange={onChangeYear}
          caretIcon={<CaretIcon />}
        />
      </div>
      <div className="form__item">
        <label htmlFor="rrs-year-menu">Financial quarter</label>
        <Select
          key={selectedYear} // Added key, will reset this RRS when selectedYear changes
          selectedValue={selectedQuarter}
          name="quarters"
          options={quarters}
          onChange={onChangeQuarter}
          caretIcon={<CaretIcon />}
        />
      </div>
      <button type="button" onClick={onReset}>
        Reset
      </button>
    </form>
  );
};

function App() {
  const [count, setCount] = React.useState(0);
  return <ControlledExample key={count} onReset={() => setCount(count + 1)} />;
}

<App />;

```

**Comment by Buba21** [comment]
Hi ben, i tried using the key prop as a way to control the re-render of the select as you suggested and it worked like a charm. Im still new with react so did not know you could use the keys as a way to control the render of an object.
Thank you so much for your help on this matter.
Keep up the good work with this amazing lib.

**Comment by benbowes** [comment]
Thanks @Buba21 👍 

I think you did uncover some unexpected behaviour though. I don't have a fix for that yet.

**Comment by benbowes** [comment]
@Buba21 do I might add the reset button as per the above example. I think it will help other users.

**Comment by benbowes** [comment]
PR's are welcome btw

**Comment by benbowes** [comment]
Version 7.0.0 requires you to have a `key` prop to change the internal state of react-responsive-select. So this is no longer considered an issue
