### ISSUE TITLE
Move data fetching code or side effects to componentDidUpdate.

### ISSUE THREAD

**Issue by ArshakKocharyan** [benbowes/react-responsive-select#156]
![Снимок экрана 2021-03-14 в 23 54 12](https://user-images.githubusercontent.com/69091971/111082258-c2e27200-8520-11eb-9513-fd5960ae3ac7.png)

index.js:1 Warning: Using UNSAFE_componentWillReceiveProps in strict mode is not recommended and may indicate bugs in your code. See https://reactjs.org/link/unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://reactjs.org/link/derived-state

Please update the following components: Select

**Comment by benbowes** [comment]
@ArshakKocharyan PR's welcome

**Comment by benbowes** [comment]
Possibly I should remove this function altogether, update a major version and enforce the use of a `key` prop along with only supporting a controlled mode

**Comment by benbowes** [comment]
https://github.com/benbowes/react-responsive-select/pull/158

**Comment by ArshakKocharyan** [comment]
Yes you can try.

**Comment by benbowes** [comment]
@ArshakKocharyan Released react-responsive-select@7.0.0
