### ISSUE TITLE
Full page crash when empty array given as options

### ISSUE THREAD

**Issue by rex-iotum** [benbowes/react-responsive-select#163]
Version: 7.0.2

If we supply an empty array as `options`, the Select crashes the app with `Cannot read property 'text' of undefined`.

Please still render the dropdown with some placeholder defaults instead of crashing the javascript.

React-Select for example has placeholder defaults when supplied an empty array.

Codesandbox (Change line 10 to be an empty array):
https://codesandbox.io/s/empty-star-l6mpv?file=/src/App.js

**Comment by benbowes** [comment]
Thanks for the example @rex-iotum sounds like a good plan

**Comment by benbowes** [comment]
PR here @rex-iotum https://github.com/benbowes/react-responsive-select/pull/165
