### ISSUE TITLE
Select component doesn't re-render when options are changed

### ISSUE THREAD

**Issue by rex-iotum** [benbowes/react-responsive-select#164]
Version: 7.0.2

If you supply a new set of `options` to the Select component, the component does not re-render with the new set of options.

React-Select for example re-renders the options dropdown when the options are changed.

Codesandbox (Click "Change Options"):
https://codesandbox.io/s/blazing-bush-oc8j8?file=/src/App.js

**Comment by benbowes** [comment]
You have to provide a `key` prop to make the Select re-render now from version 7.

```
<Select
        // set `key` to something that changes
        key={options[0].text}
        options={options}
        onChange={(newValue) => console.log("onChange", newValue)}
      />
```

**Comment by rex-iotum** [comment]
Please document that prop in your API docs

**Comment by benbowes** [comment]
It is documented here https://www.npmjs.com/package/react-responsive-select see **Upgrade from v6 - v7**

But I will add something to the API docs as well as it has tripped someone up 👍
