### ISSUE TITLE
isEqual very very slow with markup

### ISSUE THREAD

**Issue by cvlmtg** [benbowes/react-responsive-select#166]
Hi, I'm trying react-responsive-select and found it to be unbearably slow with my app. after digging a bit it seems the cause is the `isEqual()` function. 

I have options defined as

```jsx
  {
    markup: (<span dangerouslySetInnerHTML={{ __html: value }} />),
    text:   value,
    value
  }
```

which generates this object:

<img width="665" alt="Schermata 2021-07-09 alle 12 21 41" src="https://user-images.githubusercontent.com/6401008/125063848-43b91100-e0b0-11eb-8c93-d6b7daca9f5d.png">

the `JSON.stringify()` call inside `isEqual()` generates some megabytes long strings...

<img width="370" alt="Schermata 2021-07-09 alle 12 22 22" src="https://user-images.githubusercontent.com/6401008/125063899-592e3b00-e0b0-11eb-91eb-fba3c85e7bb1.png">

What's the reason to use JSON.stringify? isn't `a.value === b.value` enough?

**Comment by benbowes** [comment]
Hi @cvlmtg can you show me the markup that is being passed in?

I would be surprised if the size had much to do with JSON.stringify, but am happy to be proven wrong :)

**Comment by cvlmtg** [comment]
hi @benbowes , the markup is quite simple:

```jsx
function renderOption(value) {
  const html = { __html: value };

  return {
    markup: (<span dangerouslySetInnerHTML={html} />),
    text:   value,
    value
  };
}
```

where currently `value` is a simple string like `"manzoni"` (but could be something like `"<b>manzoni</b>"`)

but the object passed to `isEqual` is:

<img width="480" alt="Schermata 2021-07-11 alle 19 10 12" src="https://user-images.githubusercontent.com/6401008/125204068-a4e11000-e27b-11eb-9d35-6d985b5b748e.png">

the problem reside in `markup._owner` which is a fairly complex objects tree, like e.g. `markup_owner.return.return.stateNode.props` which is a react component which has the app store as a prop:

<img width="240" alt="Schermata 2021-07-11 alle 19 18 40" src="https://user-images.githubusercontent.com/6401008/125204302-d3131f80-e27c-11eb-9a16-e54e43fa1268.png">

so in the end everything gets serialized, creating a huge string.

**Comment by benbowes** [comment]
@cvlmtg I see.

Possibly could add a prop which allows the user to override the inbuilt equality function with their own equality function

**Comment by benbowes** [comment]
Will think more about this...

**Comment by benbowes** [comment]
@cvlmtg  I will checkout if a.value === b.value is enough

**Comment by cvlmtg** [comment]
@benbowes AFAIK `value` is like a unique id for each option of a select. If I create a select with two equal values, that's my mistake, so I see no reason why someone should need something else to identify the selected option. That's my humble opinion of course :)

**Comment by benbowes** [comment]
You are absolutely right @cvlmtg 

I have setup a PR https://github.com/benbowes/react-responsive-select/pull/167/files

**Comment by benbowes** [comment]
7.0.4 has been released to npm @cvlmtg 

Let me know if this helped perf if you can

**Comment by benbowes** [comment]
Also... thanks for the help!

**Comment by cvlmtg** [comment]
@benbowes sorry for the late reply, been on holiday for a few days :D I'll test the new release ASAP. thanks for the fix!

**Comment by benbowes** [comment]
My pleasure @cvlmtg let me know how it goes

**Comment by cvlmtg** [comment]
@benbowes just tried it, there is no longer any delay. thanks!

**Comment by benbowes** [comment]
I am filled with joy @cvlmtg !

Thanks for trying it out, and also thanks for your awesome suggestion ❤️
