### ISSUE TITLE
Error on Import

### ISSUE THREAD

**Issue by AlpZero** [benbowes/react-responsive-select#26]
Module not found: Can't resolve 'lodash.isequal' in '\node_modules\react-responsive-select\dist'

**Comment by AlpZero** [comment]
" yarn add lodash.isequal " solved the issue. Closing

**Comment by benbowes** [comment]
Thanks @AlpZero this is valid. I will address this

**Comment by benbowes** [comment]
Addressed in https://github.com/benbowes/react-responsive-select/pull/27 by making `lodash.isequal` a dependency. Thanks for your feedback.
