### ISSUE TITLE
Scrollbar closing the dropdown

### ISSUE THREAD

**Issue by bezchristo** [benbowes/react-responsive-select#46]
When using the scrollbar in the dropdown to scroll it closes the dropdown instead of scrolling.
The only way to currently scroll through the dropdown list is by using the scroll wheel on the mouse.

The effect can be seen in this [codepen](https://codepen.io/benbowes/pen/MEoYvd)

I'm using the latest version of Chrome, but I get the same issue on Brave, Firefox ans Edge.

**Comment by benbowes** [comment]
Thanks @bezchristo

I can see this issue and will fix it in the next few days.

**Comment by benbowes** [comment]
Hi @bezchristo 

This has been fixed in https://github.com/benbowes/react-responsive-select/pull/47

npm version 3.0.5 is now published.
