### ISSUE TITLE
'disabled' prop not initialising event listeners after componentDidMount is called

### ISSUE THREAD

**Issue by thedistricts** [benbowes/react-responsive-select#57]
1. ReactResponsiveSelect component is initially 'disabled' 
2. 'disabled' prop is passed as false so the component is active. 
3. The dropdown fails to receive any mouse events. 

Looks as though the mouse event listeners are setup in componentDidMount. If disabled is true at the point they hit this, they aren't initialised and with no opportunity to initialise them again. 

Current work around: add a key to component that changes when disabled/active forcing the component to remount

**Comment by benbowes** [comment]
Hi @thedistricts I understand what you are talking about. Did you have any thoughts on how to address this?

**Comment by benbowes** [comment]
I've added a disabled checkbox to this codepen https://codepen.io/benbowes/pen/baKoBQ?editors=0010 It shows up the issue. I'll look into it

**Comment by benbowes** [comment]
Whilst working on this I realise that the disabled scenario is not reading out well for screen readers. I will sort this out as well. I expect to be done in a few days.

Let me know if you'd like to review the PR.

**Comment by benbowes** [comment]
https://github.com/benbowes/react-responsive-select/pull/58

**Comment by benbowes** [comment]
`3.0.3` now released to [npm](https://www.npmjs.com/package/react-responsive-select) including work done in https://github.com/benbowes/react-responsive-select/pull/58, and the controlled example on (codepen controlled example)[https://codepen.io/benbowes/pen/baKoBQ?editors=0010] looks to be working as I had expected.

I did keep the component focusable, but added an aria-disabled attribute to call out it's inability to be interacted with.

Gonna close this issue for now. Let me know if anything is outstanding.

Thanks heaps for bringing this up @thedistricts 👍

**Comment by thedistricts** [comment]
Amazing! Thanks for the super quick turn around on this @benbowes

**Comment by benbowes** [comment]
Cheers 👍
