### ISSUE TITLE
Feature: ability to pass optional onclick to option list item

### ISSUE THREAD

**Issue by thedistricts** [benbowes/react-responsive-select#61]
Suggestion: 

When working with a controlled state select component, allow a function to be called when an option is selected. 

Example use case:

Allow select all / clear of options belonging to a brand by allowing a callback function to be called in the parent scope

![ezgif-5-b48606cc67](https://user-images.githubusercontent.com/478837/35802557-766c9d64-0a68-11e8-8e48-bd2f0c1be7fb.gif)

**Comment by benbowes** [comment]
I like this. Will look into it

**Comment by benbowes** [comment]
I've had a look into this and have decided not to add this feature as I believe the onChange handler should be enough to add this ability.

I am also worried about adding this due to the potentially difficult accessibility this could introduce.
