### ISSUE TITLE
Feature: ability to pass a header component to display before the options items

### ISSUE THREAD

**Issue by thedistricts** [benbowes/react-responsive-select#62]
When working with a controlled state select component, allow a component to be rendered before the options listing

use case: 

Allow controlling state to be updated without selecting an option

![ezgif-5-8475bf4d83](https://user-images.githubusercontent.com/478837/35802808-7f958954-0a69-11e8-917b-0a5292cdc350.gif)

**Comment by benbowes** [comment]
I am concerned about the accessibility implications with this one. Given that this component was built for being accessible. I am thinking this is a no for now.
