### ISSUE TITLE
onChange event not called when selectedValue === index value

### ISSUE THREAD

**Issue by litzenberger** [benbowes/react-responsive-select#64]
In the case where the index of options equals the selected value, the onChange event is called and the component will stop that event until refresh.

There is a check here that doesn't make sense to me.  There are times where a selectedValue will === the index which fails to call the onChange.
https://github.com/benbowes/react-responsive-select/blob/master/src/ReactResponsiveSelect.js#L71

I made a change but need permission to push up my change.

Thanks

**Comment by benbowes** [comment]
Thanks @litzenberger, will check this out.

**Comment by benbowes** [comment]
@litzenberger any chance you could show me the configuration you used to uncover the bug?

**Comment by litzenberger** [comment]
Hi @benbowes, thanks for looking at this.

Here is an example you can test with:
```
         options={[
            { text: 'ALL', value: 'ALL' },
            { text: 'This option breaks', value: 1, markup: <span>warning</span> },
            { text: 'This will work', value: 2 }
          ]}
```
1) Select value 1 option.
2) then unselect option 1.  It will stay on value 1 and the onChange will not be fired if selecting another option.

**Comment by benbowes** [comment]
Hi @litzenberger ,

The problem is that the `option.value` is a `number`, change it to a `string`.

Did you check the console output? It is printing `Warning: Failed prop type: Invalid prop `options[1].value` of type `number` supplied to `SingleSelect`, expected `string``

**Comment by litzenberger** [comment]
Yes, changing it to a string will work but so does padding the integer so that index will never match the selectedValue.  Is there a reason value has to be a string?

I was using multiselect and do not see a warning in console.

Thanks!

**Comment by benbowes** [comment]
The multiselect mode should give a warning about the string prop not being a string. That needs to be sorted.

I'd like to know why do you think it shouldn't be a string? What benefits may present themselves by changing the interface?

**Comment by litzenberger** [comment]
Yeah, no benfiit just something I missed when implemeting the component.

I'll go ahead and close this issue.

Thanks again.

**Comment by benbowes** [comment]
Cheers for finding the props bug. That needs to be fixed. 👍
