### ISSUE TITLE
Is there a plan to bring the lib to React v16?

### ISSUE THREAD

**Issue by zoeng** [benbowes/react-responsive-select#65]
Can you please kindly point me to the right direction if I have to make this work in react v16?

**Comment by benbowes** [comment]
Absolutely. I made an assumption that it would given the peerDependencies declaration. Will double check in a few hours and get back to you.

**Comment by benbowes** [comment]
Hi @zoeng you should not need to do anything special.

I am declaring React as a peerDependency, meaning that whatever React version you have will be used. Though the react version must be either `0.14.9` or greater than `15.3.0` as listed in the peerDependencies.

Does this answer your question?

**Comment by zoeng** [comment]
Hello Ben,

Thank you so much for your quick response.  First, I would like to say thank you for such a wonderful library that is ADA compliant.

Our project uses react v16.  The select works perfect by itself but when we try to include that within the react-modal, it breaks react-modal.  In other ways, nothing will be displayed or show up within the modal.  As if props.children does not exists.  If you have any ideas how we may able to fix the issue, please let me know.

Thanks again for quick response.
zoe



Zoe Ng

Principal Engineer




S A P I E N T
R A Z O R F I S H _



2001 The Embarcadero,
San Francisco, CA 94133, USA



T

+1 415 369 6405

M

+1 415 635 5964




The information transmitted is intended only for the person or entity to which it is addressed and may contain confidential and/or privileged material. Any review, retransmission, dissemination or other use of, or taking of any action in reliance upon, this information by persons or entities other than the intended recipient is prohibited. If you received this in error, please contact the sender and delete the material from any computer.

**Comment by benbowes** [comment]
Is there an example codepen I can look at, or something similar?

**Comment by benbowes** [comment]
@zoeng I am going to close this issue as not enough info has been supplied.

**Comment by benbowes** [comment]
@zoeng I am going to close this issue as not enough info has been supplied.
