### ISSUE TITLE
Disable individual options

### ISSUE THREAD

**Issue by jstein-ftdi** [benbowes/react-responsive-select#73]
I have a use case in which I would like individual options to be visible in the list, but not able to be selected. Would be nice (for me) if RRS had this capability. Thanks!

**Comment by benbowes** [comment]
Nice idea

**Comment by martyan** [comment]
I needed to use disabled options in my project as well. So here is PR with my implementation #81

**Comment by benbowes** [comment]
https://github.com/benbowes/react-responsive-select/pull/81 merged and published as 4.1.0
