### ISSUE TITLE
Feature suggestion: empty item

### ISSUE THREAD

**Issue by robdmoore** [benbowes/react-responsive-select#77]
It would be useful to be able to define the label for the default / empty / first item separate to the `options` array for situations where you have a list of items to select from, but it's optional to select an item or you don't want any of them selected by default.

**Comment by robdmoore** [comment]
In the meantime it's easy enough to achieve this like so:

```typescript
options={[{ value: null, text: 'All', markup: option('All') }].concat(yourArrayOfRealOptions)}
```

**Comment by benbowes** [comment]
@robdmoore I agree.

**Comment by benbowes** [comment]
I have this marked for end of July as part of https://github.com/benbowes/react-responsive-select/issues/76

**Comment by benbowes** [comment]
I have tackled this as part of https://github.com/benbowes/react-responsive-select/pull/84
