### ISSUE TITLE
Browser IE can't click on dropdown menu scrollbar

### ISSUE THREAD

**Issue by gks66** [benbowes/react-responsive-select#89]
The dropdown will close when click on scrollbar.

**Comment by benbowes** [comment]
Hi @gks66, which version (s) of  IE did you notice this on?
Cheers

**Comment by gks66** [comment]
Hi @benbowes, IE 11.

**Comment by benbowes** [comment]
Hi @gks66 I believe this is fixed as part of https://github.com/benbowes/react-responsive-select/pull/90

And published to react-responsive-select@4.3.3

Feel free to reopen

Thanks for the heads up 👍

**Comment by gks66** [comment]
Hi @benbowes it is fixed now, awesome! Thanks
